services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: pet-shelter-mssql
    environment:
      SA_PASSWORD: "Password_123#" # Пароль должен соответствовать требованиям MSSQL
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer" # Можно использовать "Express" или другую лицензию при необходимости
      MSSQL_DATABASE: "PetShalter" # Имя базы данных, которая будет создана
    ports:
      - "1433:1433" # Порт по умолчанию для MSSQL
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app-network

  react-client:
    build:
      context: ./pet-shelter
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    container_name: pet-shelter-client
    environment:
      VITE_REACT_APP_API_URL: "http://server:3000/api/"
    networks:
      - app-network

  server:
    build:
      context: ./pet-shelter-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: pet-shelter-server
    environment:
      JWT_ACCESS_SECRET: "123"
      JWT_ACCESS_LIFETIME: "7200s"
      JWT_REFRESH_SECRET: "321"
      JWT_REFRESH_LIFETIME: "7200s"
      DATABASE_URL: "sqlserver://pet-shelter-mssql:1433;database=PetShalter;user=sa;password=Password_123#;encrypt=true;trustServerCertificate=true"
      CLIENT_URL: "http://localhost:3001"
      SUPABASE_URL: "https://gmunxderffsdpoclsbjj.supabase.co"
      SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtdW54ZGVyZmZzZHBvY2xzYmpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MzE5ODksImV4cCI6MjA1MDIwNzk4OX0.trRHRDMPRbGv3SYgDp9yo7tXMPo2HffuezSHZgj8kqs"
    depends_on:
      - mssql
    networks:
      - app-network

volumes:
  mssql_data: # Определение тома для MSSQL

networks:
  app-network:
    driver: bridge
